/* 
 * Polygon API
 *
 * The future of fintech.
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
#![allow(unused_imports)]

use serde_json::Value;
use bigdecimal::BigDecimal;
use chrono::{NaiveDateTime, DateTime, FixedOffset, Utc};

use crate::models::*;
//use crate::date_serializer;
//use crate::datetime_serializer;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct InlineResponse20020 {
  #[serde(rename = "status")]
  status: String,  // OK 
  #[serde(rename = "ticker")]
  ticker: Option<CryptoSnapshotTicker> 
}

impl InlineResponse20020 {
  pub fn new(status: String, ) -> InlineResponse20020 {
    InlineResponse20020 {
      status: status,
      ticker: None
    }
  }

  pub fn set_status(&mut self, status: String) {
    self.status = status;
  }

  pub fn with_status(mut self, status: String) -> InlineResponse20020 {
    self.status = status;
    self
  }

  pub fn status(&self) -> &String {
    &self.status
  }


  pub fn set_ticker(&mut self, ticker: CryptoSnapshotTicker) {
    self.ticker = Some(ticker);
  }

  pub fn with_ticker(mut self, ticker: CryptoSnapshotTicker) -> InlineResponse20020 {
    self.ticker = Some(ticker);
    self
  }

  pub fn ticker(&self) -> Option<&CryptoSnapshotTicker> {
    self.ticker.as_ref()
  }

  pub fn reset_ticker(&mut self) {
    self.ticker = None;
  }

}


